/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.benxiaopao.thrift.model;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-04-24")
public class TPListRestaurant implements org.apache.thrift.TBase<TPListRestaurant, TPListRestaurant._Fields>, java.io.Serializable, Cloneable, Comparable<TPListRestaurant> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TPListRestaurant");

  private static final org.apache.thrift.protocol.TField PAGINATION_FIELD_DESC = new org.apache.thrift.protocol.TField("pagination", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField RESTAURANT_FIELD_DESC = new org.apache.thrift.protocol.TField("restaurant", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TPListRestaurantStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TPListRestaurantTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable TPPagination pagination; // required
  public @org.apache.thrift.annotation.Nullable TPRestaurant restaurant; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PAGINATION((short)1, "pagination"),
    RESTAURANT((short)2, "restaurant");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PAGINATION
          return PAGINATION;
        case 2: // RESTAURANT
          return RESTAURANT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PAGINATION, new org.apache.thrift.meta_data.FieldMetaData("pagination", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TPPagination.class)));
    tmpMap.put(_Fields.RESTAURANT, new org.apache.thrift.meta_data.FieldMetaData("restaurant", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TPRestaurant.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TPListRestaurant.class, metaDataMap);
  }

  public TPListRestaurant() {
  }

  public TPListRestaurant(
    TPPagination pagination,
    TPRestaurant restaurant)
  {
    this();
    this.pagination = pagination;
    this.restaurant = restaurant;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TPListRestaurant(TPListRestaurant other) {
    if (other.isSetPagination()) {
      this.pagination = new TPPagination(other.pagination);
    }
    if (other.isSetRestaurant()) {
      this.restaurant = new TPRestaurant(other.restaurant);
    }
  }

  public TPListRestaurant deepCopy() {
    return new TPListRestaurant(this);
  }

  @Override
  public void clear() {
    this.pagination = null;
    this.restaurant = null;
  }

  @org.apache.thrift.annotation.Nullable
  public TPPagination getPagination() {
    return this.pagination;
  }

  public TPListRestaurant setPagination(@org.apache.thrift.annotation.Nullable TPPagination pagination) {
    this.pagination = pagination;
    return this;
  }

  public void unsetPagination() {
    this.pagination = null;
  }

  /** Returns true if field pagination is set (has been assigned a value) and false otherwise */
  public boolean isSetPagination() {
    return this.pagination != null;
  }

  public void setPaginationIsSet(boolean value) {
    if (!value) {
      this.pagination = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public TPRestaurant getRestaurant() {
    return this.restaurant;
  }

  public TPListRestaurant setRestaurant(@org.apache.thrift.annotation.Nullable TPRestaurant restaurant) {
    this.restaurant = restaurant;
    return this;
  }

  public void unsetRestaurant() {
    this.restaurant = null;
  }

  /** Returns true if field restaurant is set (has been assigned a value) and false otherwise */
  public boolean isSetRestaurant() {
    return this.restaurant != null;
  }

  public void setRestaurantIsSet(boolean value) {
    if (!value) {
      this.restaurant = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case PAGINATION:
      if (value == null) {
        unsetPagination();
      } else {
        setPagination((TPPagination)value);
      }
      break;

    case RESTAURANT:
      if (value == null) {
        unsetRestaurant();
      } else {
        setRestaurant((TPRestaurant)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PAGINATION:
      return getPagination();

    case RESTAURANT:
      return getRestaurant();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PAGINATION:
      return isSetPagination();
    case RESTAURANT:
      return isSetRestaurant();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TPListRestaurant)
      return this.equals((TPListRestaurant)that);
    return false;
  }

  public boolean equals(TPListRestaurant that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_pagination = true && this.isSetPagination();
    boolean that_present_pagination = true && that.isSetPagination();
    if (this_present_pagination || that_present_pagination) {
      if (!(this_present_pagination && that_present_pagination))
        return false;
      if (!this.pagination.equals(that.pagination))
        return false;
    }

    boolean this_present_restaurant = true && this.isSetRestaurant();
    boolean that_present_restaurant = true && that.isSetRestaurant();
    if (this_present_restaurant || that_present_restaurant) {
      if (!(this_present_restaurant && that_present_restaurant))
        return false;
      if (!this.restaurant.equals(that.restaurant))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPagination()) ? 131071 : 524287);
    if (isSetPagination())
      hashCode = hashCode * 8191 + pagination.hashCode();

    hashCode = hashCode * 8191 + ((isSetRestaurant()) ? 131071 : 524287);
    if (isSetRestaurant())
      hashCode = hashCode * 8191 + restaurant.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TPListRestaurant other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPagination()).compareTo(other.isSetPagination());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPagination()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pagination, other.pagination);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRestaurant()).compareTo(other.isSetRestaurant());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRestaurant()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.restaurant, other.restaurant);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TPListRestaurant(");
    boolean first = true;

    sb.append("pagination:");
    if (this.pagination == null) {
      sb.append("null");
    } else {
      sb.append(this.pagination);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("restaurant:");
    if (this.restaurant == null) {
      sb.append("null");
    } else {
      sb.append(this.restaurant);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (pagination != null) {
      pagination.validate();
    }
    if (restaurant != null) {
      restaurant.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TPListRestaurantStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TPListRestaurantStandardScheme getScheme() {
      return new TPListRestaurantStandardScheme();
    }
  }

  private static class TPListRestaurantStandardScheme extends org.apache.thrift.scheme.StandardScheme<TPListRestaurant> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TPListRestaurant struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PAGINATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.pagination = new TPPagination();
              struct.pagination.read(iprot);
              struct.setPaginationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESTAURANT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.restaurant = new TPRestaurant();
              struct.restaurant.read(iprot);
              struct.setRestaurantIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TPListRestaurant struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.pagination != null) {
        oprot.writeFieldBegin(PAGINATION_FIELD_DESC);
        struct.pagination.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.restaurant != null) {
        oprot.writeFieldBegin(RESTAURANT_FIELD_DESC);
        struct.restaurant.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TPListRestaurantTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TPListRestaurantTupleScheme getScheme() {
      return new TPListRestaurantTupleScheme();
    }
  }

  private static class TPListRestaurantTupleScheme extends org.apache.thrift.scheme.TupleScheme<TPListRestaurant> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TPListRestaurant struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPagination()) {
        optionals.set(0);
      }
      if (struct.isSetRestaurant()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPagination()) {
        struct.pagination.write(oprot);
      }
      if (struct.isSetRestaurant()) {
        struct.restaurant.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TPListRestaurant struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.pagination = new TPPagination();
        struct.pagination.read(iprot);
        struct.setPaginationIsSet(true);
      }
      if (incoming.get(1)) {
        struct.restaurant = new TPRestaurant();
        struct.restaurant.read(iprot);
        struct.setRestaurantIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

